Adding retry attempt to caget
slaclab/pysmurf pull request #590
Opened 2021-01-22 19:06 UTC by eyyoung24

## Issue
Solves #589 

## Description

Catches and retries if `epics.caget` returns None. 

## Does this PR break any interface?
- [ ] Yes
- [x] No

### Which interface changed?
[Indicate here what is the interface that changed, preferable with a link to the code where the interface is defined]

### What was the interface before the change
[Describe here how was the original interface]

### What will be the new interface after the change
[Describe here how is the new interface, and what the difference with the original interface]

2021-01-28 00:04 UTC, jesusvasquez333 requested changes

2021-01-29 01:14 UTC, eyyoung24 commented on python/pysmurf/client/command/smurf_command.py
> +                    ret = epics.caget(cmd, count=count, **kwargs)
See updates

2021-01-29 01:34 UTC, jesusvasquez333 approved these changes

2021-01-29 07:18 UTC, swh76 approved these changes

2021-01-29 07:23 UTC, merged