speed up make_freq_mask
slaclab/pysmurf pull request #663
Opened 2021-06-11 04:39 UTC by jlashner

## Issue
This PR should greatly speed up the creation of frequency mask by changing the required number of epics get requests from  being proportional to the number of channels to being proportional to the number of bands. This use to take ~minutes for a full UFM.  Resolves #662 .

This has not been tested yet, so I'll test when we have a cold system available (or someone else on SO can test before then) and then we can switch this from a draft to a full PR when it works.
## Description
The current implementation of this function makes a number of epics requests for each channel, which takes a very long time when there are a lot of channels. The new version uses the centerFrequencyArray registers etc. to get info for all channels in a given band at once, which should speed it up a lot.

## Does this PR break any interface?
- [ ] Yes
- [X] No

2021-07-07 00:41 UTC, jlashner commented
Just tested on smurf-srv20 and confirmed the freq mask generated by this branch is the same, while greatly speeding up its generation.

2021-07-16 05:00 UTC, swh76 requested changes

2021-07-16 05:00 UTC, swh76 commented on python/pysmurf/client/util/smurf_util.py
> +        channel : int, None, or array
Sorry, just to hold to docstring convention, could you just change to `channel : int, None, or array, optional, default None`?

2021-07-16 16:45 UTC, jlashner commented
Alright, docstrings are fixed!

2021-07-16 18:41 UTC, swh76 approved these changes

2021-07-16 18:42 UTC, merged